package planner

import (
	"errors"
	"strings"
	"testing"

	"github.com/atulsinha87/partitionctl/engine/protocol"
)

const parentIndexName = "orders_created_at_idx"

// TestIndexConditionClassification is FR-PLAN-4: absent plus the four states
// the three pg_index flags can put an existing index in.
func TestIndexConditionClassification(t *testing.T) {
	tests := []struct {
		name                    string
		valid, ready, live      bool
		want                    IndexCondition
		wantUsable, wantCleanup bool
	}{
		{"valid ready live", true, true, true, IndexValid, true, false},
		{"interrupted CIC leaves indisvalid false", false, true, true, IndexInvalid, false, true},
		{"build still in flight", true, false, true, IndexNotReady, false, true},
		{"drop in flight", true, true, false, IndexNotLive, false, true},
		{"not live wins over not valid", false, false, false, IndexNotLive, false, true},
		{"not valid wins over not ready", false, false, true, IndexInvalid, false, true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			i := idx(1, "public", "x", 2, "t", tc.valid, tc.ready, tc.live)
			if got := i.Condition(); got != tc.want {
				t.Fatalf("Condition() = %q, want %q", got, tc.want)
			}
			if got := tc.want.Usable(); got != tc.wantUsable {
				t.Errorf("%q.Usable() = %v, want %v", tc.want, got, tc.wantUsable)
			}
			if got := tc.want.NeedsCleanup(); got != tc.wantCleanup {
				t.Errorf("%q.NeedsCleanup() = %v, want %v", tc.want, got, tc.wantCleanup)
			}
		})
	}

	t.Run("absent is neither usable nor cleanable", func(t *testing.T) {
		if IndexAbsent.Usable() || IndexAbsent.NeedsCleanup() {
			t.Error("IndexAbsent should require nothing")
		}
	})

	t.Run("every condition is enumerated", func(t *testing.T) {
		all := AllIndexConditions()
		if len(all) != 5 {
			t.Fatalf("AllIndexConditions() = %v, want 5 entries", all)
		}
		seen := map[IndexCondition]bool{}
		for _, c := range all {
			if seen[c] {
				t.Errorf("duplicate condition %q", c)
			}
			seen[c] = true
			if c.String() != string(c) {
				t.Errorf("String() = %q", c.String())
			}
		}
	})
}

// TestInspectChildrenDetectsEveryState is the FR-PLAN-4 sweep across one tree:
// each leaf carries an index in a different state, plus one with none at all.
func TestInspectChildrenDetectsEveryState(t *testing.T) {
	leaves := []string{"orders_absent", "orders_valid", "orders_invalid", "orders_notready", "orders_notlive"}
	f := tree(protocol.StrategyRange, leaves...)
	topo := mustDiscover(t, f)

	parentIdx := Index{
		OID: indexBase, Name: name("public", parentIndexName), Kind: RelKindPartitionedIndex,
		OwnerOID: ownerOID, TableOID: rootOID, Table: name("public", "orders"),
		IsValid: false, IsReady: true, IsLive: true,
	}
	f.AddIndex(parentIdx)

	// leaves[0] deliberately has no index at all.
	states := []struct {
		leaf               int
		valid, ready, live bool
		attach             bool
		want               IndexCondition
	}{
		{1, true, true, true, true, IndexValid},
		{2, false, true, true, false, IndexInvalid},
		{3, true, false, true, false, IndexNotReady},
		{4, true, true, false, false, IndexNotLive},
	}
	for _, s := range states {
		leafRel := topo.Leaves[s.leaf]
		child := idx(indexBase+10+uint32(s.leaf), "public",
			protocol.ChildIndexName(parentIndexName, leafRel.Name.Name),
			leafRel.OID, leafRel.Name.Name, s.valid, s.ready, s.live)
		if s.attach {
			child.ParentIndexOID = parentIdx.OID
		}
		f.AddIndex(child)
	}

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	if in.ParentIndex == nil || in.ParentIndex.OID != parentIdx.OID {
		t.Fatalf("ParentIndex = %+v, want the partitioned index", in.ParentIndex)
	}
	if len(in.Children) != len(leaves) {
		t.Fatalf("Children = %d, want %d", len(in.Children), len(leaves))
	}

	if in.Children[0].Exists() {
		t.Errorf("leaf %s should have no index", in.Children[0].Leaf)
	}
	if got := in.Children[0].Condition; got != IndexAbsent {
		t.Errorf("absent leaf condition = %q", got)
	}
	for _, s := range states {
		c := in.Children[s.leaf]
		if !c.Exists() {
			t.Fatalf("leaf %s has no index", c.Leaf)
		}
		if c.Condition != s.want {
			t.Errorf("leaf %s condition = %q, want %q", c.Leaf, c.Condition, s.want)
		}
		if got := c.AttachedTo(parentIdx.OID); got != s.attach {
			t.Errorf("leaf %s AttachedTo = %v, want %v", c.Leaf, got, s.attach)
		}
	}

	// FR-PLAN-5: only the one valid, attached leaf is complete.
	if got := in.CompleteCount(); got != 1 {
		t.Errorf("CompleteCount = %d, want 1", got)
	}
	if got := len(in.Remaining()); got != len(leaves)-1 {
		t.Errorf("Remaining = %d, want %d", got, len(leaves)-1)
	}
}

// TestInspectChildrenNames covers FR-PLAN-11 and FR-PLAN-13: names are
// generated by the planner, live in the leaf's schema, and are recorded rather
// than re-derived.
func TestInspectChildrenNames(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	for i, c := range in.Children {
		want := childIndex(t, parentIndexName, topo.Leaves[i].Name.Name)
		if c.ChildIndex != want {
			t.Errorf("child %d = %v, want %v", i, c.ChildIndex, want)
		}
		if c.ChildIndex.Schema != c.Leaf.Name.Schema {
			t.Errorf("child index %v is not in its leaf's schema %q", c.ChildIndex, c.Leaf.Name.Schema)
		}
		if err := c.ChildIndex.Validate(); err != nil {
			t.Errorf("generated name %v is not a legal identifier: %v", c.ChildIndex, err)
		}
	}
}

// TestInspectChildrenRejectsNameCollision: FR-PLAN-13 wants a plan-time error,
// never a silent overwrite.
func TestInspectChildrenRejectsNameCollision(t *testing.T) {
	// Two partitions whose names differ only past the truncation point, under
	// a parent index name long enough to force truncation, still get distinct
	// names because the tag hashes the untruncated inputs. Proving the
	// collision path therefore needs two identical partition names, which the
	// catalog cannot produce; assert the guarantee ChildIndexNames gives
	// instead.
	long := strings.Repeat("p", 55)
	f := tree(protocol.StrategyRange, long+"_january", long+"_february")
	topo := mustDiscover(t, f)

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	a, b := in.Children[0].ChildIndex, in.Children[1].ChildIndex
	if a == b {
		t.Fatalf("two partitions collided on %v", a)
	}
	for _, n := range []protocol.ObjectName{a, b} {
		if len(n.Name) > protocol.MaxIdentifierBytes {
			t.Errorf("%v is %d bytes, over the identifier limit", n, len(n.Name))
		}
	}
}

func TestInspectChildrenRejectsBadParentName(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)

	_, err := InspectChildren(ctx(), f, topo, protocol.ObjectName{})
	if !errors.Is(err, ErrInvalidSpecification) {
		t.Fatalf("err = %v, want ErrInvalidSpecification", err)
	}
}

func TestInspectChildrenParentIndexAbsent(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	if in.ParentIndex != nil {
		t.Errorf("ParentIndex = %+v, want nil", in.ParentIndex)
	}
	if in.ParentIndexOID() != 0 {
		t.Errorf("ParentIndexOID = %d, want 0", in.ParentIndexOID())
	}
	// With no parent index, nothing can be attached, so nothing is complete.
	if in.CompleteCount() != 0 {
		t.Errorf("CompleteCount = %d, want 0", in.CompleteCount())
	}
}

// TestInspectChildrenIgnoresOtherIndexes: an index on the same leaf with a
// different name is not this plan's business.
func TestInspectChildrenIgnoresOtherIndexes(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)
	f.AddIndex(idx(indexBase+1, "public", "orders_2026_01_pkey",
		leafOID(0), "orders_2026_01", true, true, true))

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	if in.Children[0].Exists() {
		t.Error("an unrelated index was matched to the generated child name")
	}
}

func TestInspectChildrenPropagatesCatalogErrors(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)
	f.Err = ErrCatalogUnavailable.Detailf("connection reset")

	if _, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName)); !errors.Is(err, ErrCatalogUnavailable) {
		t.Fatalf("err = %v, want ErrCatalogUnavailable", err)
	}
}

// TestDecideCleanup is FR-PLAN-6 versus FR-PLAN-7: ownership decides whether an
// unusable index is dropped or the run halts (AC-5, AC-6, NFR-REL-3).
//
// Ownership is read off the object, as a marker in its comment. The live claim
// is consulted only where the marker is missing, which is the crash window
// between the creating statement and the COMMENT that follows it.
func TestDecideCleanup(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)
	leaf := topo.Leaves[0]
	childName := childIndex(t, parentIndexName, leaf.Name.Name)

	plan := func(cond IndexCondition) ChildIndexPlan {
		c := ChildIndexPlan{Leaf: leaf, ChildIndex: childName, Condition: cond}
		if cond != IndexAbsent {
			existing := idx(indexBase+1, childName.Schema, childName.Name, leaf.OID, leaf.Name.Name,
				cond != IndexInvalid, cond != IndexNotReady, cond != IndexNotLive)
			c.Existing = &existing
		}
		return c
	}

	// marked/unmarked/foreign describe what the catalog says about the object.
	marked := func() *FakeCatalog { return standardTree().Mark(childName, "run-0") }
	unmarked := func() *FakeCatalog { return standardTree() }
	foreign := func() *FakeCatalog {
		return standardTree().Comment(childName, "built by the DBA team, do not touch")
	}

	tests := []struct {
		name     string
		cond     IndexCondition
		catalog  func() *FakeCatalog
		claims   ClaimLookup
		want     CleanupDecision
		wantHalt bool
	}{
		{
			name: "absent needs nothing",
			cond: IndexAbsent, catalog: marked, want: CleanupNone,
		},
		{
			name: "valid needs nothing",
			cond: IndexValid, catalog: marked, want: CleanupNone,
		},
		{
			name: "invalid and marked is dropped (FR-PLAN-6, AC-5)",
			cond: IndexInvalid, catalog: marked, want: CleanupDropWithProvenance,
		},
		{
			name: "not ready and marked is dropped",
			cond: IndexNotReady, catalog: marked, want: CleanupDropWithProvenance,
		},
		{
			name: "invalid, unmarked, with a live claim is adopted then dropped",
			cond: IndexInvalid, catalog: unmarked, claims: NewFakeClaims(childName),
			want: CleanupAdoptThenDrop,
		},
		{
			name: "invalid, unmarked, with no claim halts (FR-PLAN-7, AC-6)",
			cond: IndexInvalid, catalog: unmarked, want: CleanupHalt, wantHalt: true,
		},
		{
			name: "invalid with no claim source at all halts",
			cond: IndexInvalid, catalog: unmarked, claims: nil, want: CleanupHalt, wantHalt: true,
		},
		{
			// Never overwrite a human's comment, never drop the object under
			// it, and a live claim does not change that.
			name: "invalid under somebody else's comment halts even with a claim",
			cond: IndexInvalid, catalog: foreign, claims: NewFakeClaims(childName),
			want: CleanupHalt, wantHalt: true,
		},
		{
			// A killed DROP INDEX CONCURRENTLY leaves exactly indislive = false
			// with nothing in flight, and PostgreSQL's documented recovery is
			// to reissue the drop. Halting here instead meant `plan` plus
			// `execute` could recover from this state and `resume` could not.
			name: "not live and marked is re-dropped (FR-PLAN-6)",
			cond: IndexNotLive, catalog: marked, want: CleanupDropWithProvenance,
		},
		{
			name: "not live and unmarked halts (FR-PLAN-7, AC-6)",
			cond: IndexNotLive, catalog: unmarked, want: CleanupHalt, wantHalt: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, verdict, err := DecideCleanup(ctx(), tc.catalog(), tc.claims, plan(tc.cond))
			if got != tc.want {
				t.Errorf("decision = %q, want %q (reason: %s)", got, tc.want, verdict.Reason)
			}
			if !tc.wantHalt {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
				return
			}
			if !errors.Is(err, ErrForeignInvalidIndex) {
				t.Fatalf("err = %v, want ErrForeignInvalidIndex", err)
			}
			// AC-6 wants the halt reported, and the exit code is the
			// authorization-unsatisfied code because that is what refused.
			if code := protocol.ExitCodeFor(err); code != protocol.ExitAuthorizationUnsatisfied {
				t.Errorf("exit code = %d, want 13", code)
			}
			if !strings.Contains(err.Error(), childName.String()) {
				t.Errorf("message %q does not name the index", err.Error())
			}
		})
	}
}

// A marked object costs no state-store read at all: the marker is the answer,
// and the claim exists only to cover the window in which there is no marker.
func TestDecideCleanupOnlyReadsTheClaimWhenTheMarkerIsMissing(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)
	leaf := topo.Leaves[0]
	childName := childIndex(t, parentIndexName, leaf.Name.Name)
	existing := idx(indexBase+1, childName.Schema, childName.Name, leaf.OID, leaf.Name.Name, false, true, true)
	child := ChildIndexPlan{Leaf: leaf, ChildIndex: childName, Condition: IndexInvalid, Existing: &existing}

	claims := NewFakeClaims()
	claims.Err = errors.New("state store unreachable")

	// Marked: the claim is never consulted, so the outage is invisible.
	if got, _, err := DecideCleanup(ctx(), standardTree().Mark(childName, "run-0"), claims, child); err != nil ||
		got != CleanupDropWithProvenance {
		t.Fatalf("decision = %q, err = %v; a marked object must not need the state store", got, err)
	}

	// Unmarked: the claim is the only remaining witness, so an outage is
	// "cannot decide" and halts rather than denying quietly.
	got, _, err := DecideCleanup(ctx(), standardTree(), claims, child)
	if got != CleanupHalt {
		t.Errorf("decision = %q, want %q", got, CleanupHalt)
	}
	if err == nil || !strings.Contains(err.Error(), "state store unreachable") {
		t.Fatalf("err = %v, want the claim error propagated", err)
	}
}

func TestIndexHelpers(t *testing.T) {
	i := idx(1, "public", "child", 2, "leaf", true, true, true)
	if i.Attached() {
		t.Error("a fresh index should not be attached")
	}
	if i.AttachedTo(0) {
		t.Error("AttachedTo(0) must never be true; 0 means no parent")
	}
	i.ParentIndexOID = 7
	if !i.Attached() || !i.AttachedTo(7) || i.AttachedTo(8) {
		t.Errorf("attachment predicates wrong for %+v", i)
	}
	if i.ConstraintBacked() {
		t.Error("no constraint was set")
	}
	i.ConstraintName, i.ConstraintType = "orders_pkey", "p"
	if !i.ConstraintBacked() {
		t.Error("a constraint-backed index must be reported (FR-DROP-2)")
	}
	if i.String() != "public.child" {
		t.Errorf("String() = %q", i.String())
	}
}

func TestChildIndexPlanCompleteness(t *testing.T) {
	existing := idx(1, "public", "child", 2, "leaf", true, true, true)
	existing.ParentIndexOID = 7

	c := ChildIndexPlan{ChildIndex: name("public", "child"), Existing: &existing, Condition: IndexValid}
	if !c.Complete(7) {
		t.Error("a valid, attached index is complete work (FR-PLAN-5)")
	}
	if c.Complete(8) {
		t.Error("attached to a different parent index is not complete")
	}

	c.Condition = IndexInvalid
	if c.Complete(7) {
		t.Error("an invalid index is never complete")
	}

	empty := ChildIndexPlan{Condition: IndexAbsent}
	if empty.Exists() || empty.AttachedTo(7) || empty.Complete(7) {
		t.Error("an absent index must be absent by every predicate")
	}
}

// TestInspectChildrenAllowsSameBareNameInDifferentSchemas proves the resume
// path agrees with the plan path about what a collision is (FR-PLAN-13, AC-4).
//
// PostgreSQL permits `CREATE TABLE archive.p1 PARTITION OF public.orders`
// alongside `public.p1`, and an index lives in its table's schema, so the two
// leaves cannot collide. operations/create-index proves collision-freedom per
// schema for exactly that reason. InspectChildren, the only path `resume` has,
// must reach the same verdict, or a tree that plans and executes can never be
// resumed.
func TestInspectChildrenAllowsSameBareNameInDifferentSchemas(t *testing.T) {
	f := NewFakeCatalog()
	f.AddRole(ownerOID, "app_owner", true)
	f.AddRelation(Relation{
		OID: rootOID, Name: name("public", "orders"),
		Kind: RelKindPartitionedTable, OwnerOID: ownerOID,
	})
	f.SetStrategy(rootOID, protocol.StrategyRange)
	for i, schema := range []string{"public", "archive"} {
		f.AddRelation(Relation{
			OID: leafOID(i), Name: name(schema, "p1"),
			Kind: RelKindTable, OwnerOID: ownerOID, ParentOID: rootOID,
			PartitionBound: "FOR VALUES FROM ('2026-01-01') TO ('2026-02-01')",
		})
	}

	topo := mustDiscover(t, f)
	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren rejected a legal two-schema tree: %v", err)
	}

	seen := map[protocol.ObjectName]bool{}
	for _, c := range in.Children {
		if c.ChildIndex.Schema != c.Leaf.Name.Schema {
			t.Errorf("child index %v is not in its leaf's schema %q", c.ChildIndex, c.Leaf.Name.Schema)
		}
		if seen[c.ChildIndex] {
			t.Errorf("duplicate child index name %v", c.ChildIndex)
		}
		seen[c.ChildIndex] = true
	}
	if len(seen) != 2 {
		t.Fatalf("got %d distinct child index names, want 2", len(seen))
	}
}

// PostgreSQL propagates a partitioned index to a partition added after the
// index was built: it creates the child index immediately, under a name it
// chooses itself (orders_2026_01_created_at_idx), and attaches it. The
// partition needs no work.
//
// Keying only on this tool's generated name made that index invisible, so the
// leaf read as "needs a build". The plan that followed spent hours on a CREATE
// INDEX CONCURRENTLY and then failed terminally on ATTACH with SQLSTATE 55000,
// because a partition may carry only one attached child index per partitioned
// index. Nothing in the tool could get past it afterwards, and every attempt
// left another stray duplicate index on the partition.
func TestInspectChildrenSeesAnIndexPostgreSQLAttachedUnderItsOwnName(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)

	parentIdx := Index{
		OID: indexBase, Name: name("public", parentIndexName), Kind: RelKindPartitionedIndex,
		OwnerOID: ownerOID, TableOID: rootOID, Table: name("public", "orders"),
		IsValid: true, IsReady: true, IsLive: true,
	}
	f.AddIndex(parentIdx)

	// The server's own name for the propagated child, which is not the name
	// protocol.ChildIndexName generates.
	leaf := topo.Leaves[0]
	serverChosen := leaf.Name.Name + "_created_at_idx"
	if serverChosen == protocol.ChildIndexName(parentIndexName, leaf.Name.Name) {
		t.Fatal("the fixture's server-chosen name collides with the generated one")
	}
	propagated := idx(indexBase+50, "public", serverChosen, leaf.OID, leaf.Name.Name, true, true, true)
	propagated.ParentIndexOID = parentIdx.OID
	f.AddIndex(propagated)

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	c := in.Children[0]
	if c.Exists() {
		t.Error("the propagated index was matched to the generated child name; it has a different name")
	}
	if c.Attached == nil {
		t.Fatal("InspectChildren did not see the index PostgreSQL attached under its own name")
	}
	if c.Attached.Name.Name != serverChosen {
		t.Errorf("Attached = %s, want %s", c.Attached.Name.Name, serverChosen)
	}
	if !c.Complete(in.ParentIndexOID()) {
		t.Error("the leaf is not reported complete, so a plan would emit a doomed create+attach for it")
	}
	if n := in.CompleteCount(); n != 1 {
		t.Errorf("CompleteCount = %d, want 1", n)
	}
	if r := in.Remaining(); len(r) != len(topo.Leaves)-1 {
		t.Errorf("Remaining = %d leaves, want %d", len(r), len(topo.Leaves)-1)
	}
}

// The same propagated index, but broken. It cannot be dropped individually and
// there is no DETACH, so the leaf is neither complete nor plannable: it has to
// be reported, not walked into.
func TestInspectChildrenReportsAnUnusableForeignAttachedIndex(t *testing.T) {
	f := standardTree()
	topo := mustDiscover(t, f)

	parentIdx := Index{
		OID: indexBase, Name: name("public", parentIndexName), Kind: RelKindPartitionedIndex,
		OwnerOID: ownerOID, TableOID: rootOID, Table: name("public", "orders"),
		IsValid: false, IsReady: true, IsLive: true,
	}
	f.AddIndex(parentIdx)

	leaf := topo.Leaves[0]
	propagated := idx(indexBase+50, "public", leaf.Name.Name+"_created_at_idx",
		leaf.OID, leaf.Name.Name, false, true, true)
	propagated.ParentIndexOID = parentIdx.OID
	f.AddIndex(propagated)

	in, err := InspectChildren(ctx(), f, topo, name("public", parentIndexName))
	if err != nil {
		t.Fatalf("InspectChildren: %v", err)
	}
	c := in.Children[0]
	if c.Complete(in.ParentIndexOID()) {
		t.Error("an unusable attached index must not read as complete")
	}
	got, ok := c.ForeignAttached(in.ParentIndexOID())
	if !ok {
		t.Fatal("ForeignAttached did not report the unusable attached index")
	}
	if got.Name.Name != propagated.Name.Name {
		t.Errorf("ForeignAttached = %s, want %s", got.Name.Name, propagated.Name.Name)
	}
}
